include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - bricks/**
    # - "**/*.g.dart"
    # - "**/*.gr.dart"
    # - "**/*.freezed.dart"
    # - "**/*.config.dart"
    # - "**/generated_plugin_registrant.dart"

linter:
  rules:
    non_constant_identifier_names: false
