name: json_viewer
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"

deploy:
  name: VisaData
  # don't add hashtag at the begging
  tag: visa_test

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  isar: ^3.0.2
  shared_preferences: ^2.0.15
  
  google_fonts: ^3.0.1

  google_maps_flutter: ^2.2.2
  cupertino_icons: ^1.0.2
  go_router: ^5.2.4
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  isar_generator: ^3.0.5

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
